### ISSUE TITLE
Testing on Windows

### ISSUE THREAD

**Issue by amitkumarj441** [josmas/local-badgr-server#3]
Please review this!
I have initiated a pull request for couchbase on windows #1 
and a dockerfile(#2) for the above PR #1  

I have tested on windows and this works fine.

**Comment by josmas** [comment]
please see comments in #1

**Comment by josmas** [comment]
Can you confirm this works on windows without your changes? I don't really understand why the changes are needed.

**Comment by amitkumarj441** [comment]
Hi @josmas,

Yes, it works fine on windows only when you put the URL in my PR, i tried your existing Dockerfile in repo on windows and it gives a lot of error which seems me a tough task to debug, instead of debugging, i wrote a separate dockerfile and .sh for the same on windows and initiated it here.
Changes only on windows, this is not for linux based OS.

Thank you
Amit Kumar Jaiswal

**Comment by josmas** [comment]
sorry @amitkumarj441 but I do not understand.

You say you tried the script as it is on windows and it didn't work. Which parts did not work? Can you report errors or what you see? What are the changes needed that you mention as the _URL in my PR_?

I am going to close the PRs because there's no need to implement couchbase in this repo.

Can we try and fix the issues you see when you run the original files on windows?

**Comment by amitkumarj441** [comment]
Hi @josmas ,

I tried your code on my windows as I installed docker toolbox on my windows. I'll report it soon here. URL in my PR was in my code and it was closed.
I'll try to re-test it on window and then we'll fix it accordingly.

Thank you
Amit Kumar Jaiswal

**Comment by josmas** [comment]
Thank you @amitkumarj441 
The purpose of this repo is only to be run within docker and for development purposes; that is the only things that needs to be tested. Appreciate your help!

**Comment by amitkumarj441** [comment]
Hi @josmas ,

**Comment by amitkumarj441** [comment]
Hi @josmas ,

I'm quite busy last weekend and this week too. So, I'll do it from next week.
I accidentally messaged you on gitter, it was my misconception.

Thank you
Amit Kumar Jaiswal

**Comment by josmas** [comment]
hey @amitkumarj441 ok, not a problem. I am going to close this one for now. Whenever you have time, please reopen or start a new issue. Thanks again for your help!
